name: Build Custom LuCI App Package

on:
  push:
    branches: [ main ]
    tags:
      - "v*"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    timeout-minutes: 360

    strategy:
      matrix:
        arch: [ x86_64 ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Package
        uses: openwrt/gh-action-sdk@v5
        env:
          ARCH: ${{ matrix.arch }}-23.05.4
          CONTAINER: openwrt/sdk
          FEEDNAME: custom
          PACKAGES: luci-app-customtunnel

          EXTRA_FEEDS: "custom|${{ github.workspace }}/applications"

          BUILD_LOG: 1
          IGNORE_ERRORS: 1

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-packages
          path: bin/packages/${{ matrix.arch }}/custom/*.ipk

  release:
    name: Upload to Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Download built packages
        uses: actions/download-artifact@v4
        with:
          name: x86_64-packages
          path: ./release-ipk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-ipk/*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
